#version 330

in vec2 vertexIn;
out vec2 texCoord;

struct TestSubStructure {
	int a;
	int b;
};

struct TestStructure {
	float floater;
	TestSubStructure[2] inc;
	int inter;
	mat3 matrix;
	float nik;
	float[5] values;
};

/*struct AutogeneratedStructName {
	float field1;
};
uniform AutogeneratedStructName uniform1;
// shall be equivalent to
uniform AutogeneratedStructName {
	float field1;
} uniform1; */

void main()
{
	gl_Position = vec4(vertexIn.xy, 0.0, 1.0);
	texCoord = vertexIn.xy*0.5+0.5;
}